services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minimal-tomcat-spring-war-java17:latest
    container_name: minimal-tomcat-spring-war
    ports:
      - "8080:8080"